TRAIN_FILE = "/inputs/data/mel_spec_train/"
TRAIN_ANNOTATION = "/inputs/data/annotation_train.json"
TEST_FILE = "/inputs/data/mel_spec_test/"
TEST_ANNOTATION = "/inputs/data/annotation_test.json"
DESTINATION_FILE = "/outputs/result/"