'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/JjCcKk/hackaton.git
  CloneMustard:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    outputs:
      repomustard:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/soujanyaporia/MUStARD.git
  Preprocessing:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
      - CloneMustard
    uses: script@v1
    with:
      script: |-
        python3 /inputs/repo/preprocessing/create_test_train.py
        python3 /inputs/repo/preprocessing/dataset.py
        cp -r /inputs/repo /outputs/repo/
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29
    inputs:
      repo: CloneRepo.outputs.repo
      repomustard: CloneMustard.outputs.repomustard
      videoinit:
        type: dataset
        with:
          ref: dsmgdoydul41mbn
    outputs:
      data:
        type: volume
      repo:
        type: volume
  Model:
    resources:
      instance-type: P5000
    needs:
      - Preprocessing
    uses: script@v1
    with:
      script: |-
        echo Lancement model
        ls /inputs/repo/repo/model/
        python3 /inputs/repo/repo/model/trainCNN.py
      image: paperspace/gradient-base:tf29-pt112-py39-2022-06-29
    inputs:
      data: Preprocessing.outputs.data
      repo: Preprocessing.outputs.repo
      videoinit:
        type: dataset
        with:
          ref: dsmgdoydul41mbn
    outputs:
      res:
        type: volume