'on':
  github:
    branches:
      only: main
jobs:
  CloneRepo:
    resources:
      instance-type: C4
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/JjCcKk/hackaton.git
  CloneMustard:
    resources:
      instance-type: C4
    needs:
      - CloneRepo
    outputs:
      repomustard:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/soujanyaporia/MUStARD.git
  Preprocessing:
    resources:
      instance-type: P5000
    needs:
      - CloneRepo
      - CloneMustard
    uses: script@v1
    with:
      script: |-
        python3 /inputs/repo/preprocessing/create_test_train.py
        python3 /inputs/repo/preprocessing/dataset.py
      image: paperspace/gradient-base
    inputs:
      repo: CloneRepo.outputs.repo
      repomustard: CloneMustard.outputs.repomustard
      videoinit:
        type: dataset
        with:
          ref: dsmgdoydul41mbn
    outputs:
      data:
        type: volume